import type { ShortcutDefinition } from './types';
import { getShortcutGates } from '../stores/shortcutHandlersStore';
import { useShortcutContextStore } from '../stores/shortcutContextStore';

export const SHORTCUT_REGISTRY: ShortcutDefinition[] = [
  // Terminal-focused (highest priority)
  {
    id: 'terminal.clear',
    chord: 'mod+k',
    label: 'Clear terminal',
    scope: 'terminalFocused',
    priority: 100,
    handlerId: 'clearTerminal',
    skipInTerminal: false,
    when: () => getShortcutGates().terminalFocused,
  },

  // Monaco defers find to built-in editor
  {
    id: 'chat.find',
    chord: 'mod+f',
    label: 'Find in chat',
    scope: 'global',
    priority: 25,
    handlerId: 'openChatFind',
    skipInMonaco: true,
    when: () => !getShortcutGates().monacoFocused,
  },

  // Global
  {
    id: 'global.settings',
    chord: 'mod+,',
    label: 'Open settings',
    scope: 'global',
    priority: 20,
    handlerId: 'openSettings',
  },
  {
    id: 'global.commandPalette',
    chord: 'mod+shift+p',
    label: 'Command palette',
    scope: 'global',
    priority: 20,
    handlerId: 'openCommandPalette',
  },
  {
    id: 'global.modelLibrary',
    chord: 'mod+shift+m',
    label: 'Model library',
    scope: 'global',
    priority: 20,
    handlerId: 'openModelLibrary',
  },
  {
    id: 'global.domainPacks',
    chord: 'mod+shift+k',
    label: 'Domain packs',
    scope: 'global',
    priority: 20,
    handlerId: 'openDomainPacks',
  },
  {
    id: 'global.escape',
    chord: 'escape',
    label: 'Close overlay or stop agents',
    scope: 'global',
    priority: 95,
    allowInInput: true,
    handlerId: 'handleEscape',
  },

  // Approvals (contextual)
  {
    id: 'approvals.approve',
    chord: 'mod+enter',
    label: 'Approve first pending',
    scope: 'chat',
    priority: 85,
    handlerId: 'approveFirstPending',
    when: () => getShortcutGates().hasPendingApprovals,
  },
  {
    id: 'approvals.reject',
    chord: 'mod+backspace',
    label: 'Reject first pending',
    scope: 'chat',
    priority: 85,
    handlerId: 'rejectFirstPending',
    when: () => getShortcutGates().hasPendingApprovals,
  },

  // Thread
  {
    id: 'thread.close',
    chord: 'mod+shift+]',
    label: 'Close thread',
    scope: 'chat',
    priority: 70,
    handlerId: 'closeThread',
    when: () => getShortcutGates().threadOpen,
  },

  // IDE / dev pack
  {
    id: 'ide.quickOpen',
    chord: 'mod+p',
    label: 'Quick open file',
    scope: 'ide',
    priority: 60,
    handlerId: 'quickOpen',
    when: () => getShortcutGates().ideEnabled,
  },
  {
    id: 'ide.goToSymbol',
    chord: 'mod+shift+o',
    label: 'Go to symbol',
    scope: 'ide',
    priority: 60,
    handlerId: 'goToSymbol',
    when: () => getShortcutGates().ideEnabled,
  },
  {
    id: 'ide.fastEdit',
    chord: 'mod+k',
    label: 'Fast edit',
    scope: 'ide',
    priority: 55,
    handlerId: 'fastEdit',
    when: () =>
      getShortcutGates().ideEnabled &&
      getShortcutGates().codeEditorOpen &&
      !getShortcutGates().terminalFocused,
  },
  {
    id: 'ide.focusComposer',
    chord: 'mod+l',
    label: 'Focus composer',
    scope: 'ide',
    priority: 60,
    handlerId: 'focusComposer',
    when: () => getShortcutGates().ideEnabled && getShortcutGates().ideLayout,
  },
  {
    id: 'ide.save',
    chord: 'mod+s',
    label: 'Save file',
    scope: 'ide',
    priority: 60,
    handlerId: 'saveActiveTab',
    when: () => getShortcutGates().ideEnabled,
  },
  {
    id: 'ide.saveAll',
    chord: 'mod+shift+s',
    label: 'Save all files',
    scope: 'ide',
    priority: 60,
    handlerId: 'saveAllTabs',
    when: () => getShortcutGates().ideEnabled,
  },
  {
    id: 'ide.closeTab',
    chord: 'mod+w',
    label: 'Close editor tab',
    scope: 'ide',
    priority: 60,
    handlerId: 'closeActiveTab',
    when: () => getShortcutGates().ideEnabled,
  },
  {
    id: 'ide.openEditor',
    chord: 'mod+shift+f',
    label: 'Open code editor',
    scope: 'ide',
    priority: 55,
    handlerId: 'openCodeEditor',
    when: () => getShortcutGates().ideEnabled,
  },
  {
    id: 'ide.cycleTabForward',
    chord: 'mod+tab',
    label: 'Next editor tab',
    scope: 'ide',
    priority: 58,
    handlerId: 'cycleEditorTabForward',
    when: () => getShortcutGates().ideEnabled && getShortcutGates().codeEditorOpen,
  },
  {
    id: 'ide.cycleTabBackward',
    chord: 'mod+shift+tab',
    label: 'Previous editor tab',
    scope: 'ide',
    priority: 58,
    handlerId: 'cycleEditorTabBackward',
    when: () => getShortcutGates().ideEnabled && getShortcutGates().codeEditorOpen,
  },

  // Layout / panels
  {
    id: 'layout.channelSidebar',
    chord: 'mod+b',
    label: 'Toggle channel sidebar',
    scope: 'chat',
    priority: 40,
    handlerId: 'toggleChannelSidebar',
    when: () => getShortcutGates().chatConnected,
  },
  {
    id: 'layout.fileExplorer',
    chord: 'mod+shift+e',
    label: 'Toggle file explorer',
    scope: 'chat',
    priority: 40,
    handlerId: 'toggleFileExplorer',
    when: () => getShortcutGates().chatConnected,
  },
  {
    id: 'layout.terminal',
    chord: 'mod+j',
    label: 'Toggle terminal',
    scope: 'global',
    priority: 40,
    handlerId: 'toggleTerminal',
  },
  {
    id: 'layout.tasks',
    chord: 'mod+shift+t',
    label: 'Toggle task management',
    scope: 'chat',
    priority: 40,
    handlerId: 'toggleTaskManagement',
    when: () => getShortcutGates().chatConnected,
  },
  {
    id: 'layout.git',
    chord: 'mod+shift+g',
    label: 'Toggle Git panel',
    scope: 'chat',
    priority: 40,
    handlerId: 'toggleGitPanel',
    when: () => getShortcutGates().chatConnected && getShortcutGates().ideEnabled,
  },
  {
    id: 'layout.problems',
    chord: 'mod+shift+d',
    label: 'Toggle problems panel',
    scope: 'chat',
    priority: 40,
    handlerId: 'toggleProblemsPanel',
    when: () => getShortcutGates().chatConnected && getShortcutGates().ideEnabled,
  },
  {
    id: 'layout.pendingChanges',
    chord: 'mod+shift+u',
    label: 'Go to pending change',
    scope: 'chat',
    priority: 40,
    handlerId: 'togglePendingChanges',
    when: () => getShortcutGates().chatConnected && getShortcutGates().ideEnabled,
  },
  {
    id: 'layout.myAgents',
    chord: 'mod+shift+a',
    label: 'Toggle My Agents',
    scope: 'chat',
    priority: 40,
    handlerId: 'toggleMyAgents',
    when: () => getShortcutGates().chatConnected,
  },
  {
    id: 'layout.chatPanel',
    chord: 'mod+shift+c',
    label: 'Toggle chat panel',
    scope: 'chat',
    priority: 40,
    handlerId: 'toggleChatPanel',
    when: () => getShortcutGates().chatConnected,
  },
  {
    id: 'layout.toolbarSidebar',
    chord: 'mod+shift+\\',
    label: 'Toggle toolbar sidebar',
    scope: 'chat',
    priority: 40,
    handlerId: 'toggleToolbarSidebar',
    when: () => getShortcutGates().chatConnected,
  },
  {
    id: 'layout.ideToggle',
    chord: 'mod+shift+i',
    label: 'Toggle IDE layout',
    scope: 'chat',
    priority: 40,
    handlerId: 'toggleIdeLayout',
    when: () => getShortcutGates().chatConnected && getShortcutGates().ideEnabled,
  },
  {
    id: 'layout.newRunbook',
    chord: 'mod+shift+r',
    label: 'New runbook',
    scope: 'chat',
    priority: 40,
    handlerId: 'newRunbook',
    when: () => getShortcutGates().chatConnected,
  },

  // Navigation
  {
    id: 'nav.prevChannel',
    chord: 'alt+up',
    label: 'Previous channel',
    scope: 'chat',
    priority: 35,
    handlerId: 'prevChannel',
    when: () => getShortcutGates().chatConnected,
  },
  {
    id: 'nav.nextChannel',
    chord: 'alt+down',
    label: 'Next channel',
    scope: 'chat',
    priority: 35,
    handlerId: 'nextChannel',
    when: () => getShortcutGates().chatConnected,
  },
  {
    id: 'nav.focusSearch',
    chord: 'mod+0',
    label: 'Focus channel search',
    scope: 'chat',
    priority: 35,
    handlerId: 'focusChannelSearch',
    when: () => getShortcutGates().chatConnected,
  },
  {
    id: 'nav.createChannel',
    chord: 'mod+n',
    label: 'Create channel',
    scope: 'chat',
    priority: 35,
    handlerId: 'createChannel',
    when: () => getShortcutGates().chatConnected,
  },
  {
    id: 'nav.createDm',
    chord: 'mod+shift+n',
    label: 'New DM',
    scope: 'chat',
    priority: 35,
    handlerId: 'createNewDm',
    when: () => getShortcutGates().chatConnected,
  },
  {
    id: 'nav.workspaceSwitcher',
    chord: 'mod+shift+w',
    label: 'Workspace switcher',
    scope: 'ide',
    priority: 35,
    handlerId: 'openWorkspaceSwitcher',
    when: () => getShortcutGates().ideEnabled,
  },
];

export function getShortcutsForDisplay(): Array<{ id: string; chord: string; label: string }> {
  return SHORTCUT_REGISTRY.map(({ id, chord, label }) => ({ id, chord, label }));
}

export function hasOpenOverlay(): boolean {
  return useShortcutContextStore.getState().hasOverlay();
}
