#!/usr/bin/env python3
"""Generate desktop/src/stores/packCapabilities.generated.ts from capability_tokens.json."""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TOKENS = ROOT / "internal" / "packs" / "capability_tokens.json"
OUT = ROOT / "desktop" / "src" / "stores" / "packCapabilities.generated.ts"


def const_name(token: str) -> str:
    return token.replace("-", "_").upper()


def main() -> int:
    data = json.loads(TOKENS.read_text(encoding="utf-8"))
    platform = list(data.get("platform") or [])
    domain = list(data.get("official_domain") or [])
    local = list(data.get("pack_local_examples") or [])

    lines = [
        "/* Generated by scripts/gen-pack-capabilities.py — do not edit by hand. */",
        "/* Source: internal/packs/capability_tokens.json */",
        "",
        "/** Thin NJ platform + official domain capability tokens. */",
        "export const PACK_PLATFORM_CAP = {",
    ]
    for tok in platform + domain:
        lines.append(f"  {const_name(tok)}: '{tok}',")
    lines.append("} as const;")
    lines.append("")
    lines.append("/** Documented pack-local capability ids (capability_defs); prefer hub registry at runtime. */")
    lines.append("export const PACK_LOCAL_CAP = {")
    for tok in local:
        lines.append(f"  {const_name(tok)}: '{tok}',")
    lines.append("} as const;")
    lines.append("")
    lines.append("export const PACK_CAP = { ...PACK_PLATFORM_CAP, ...PACK_LOCAL_CAP } as const;")
    lines.append("")
    lines.append("export type PackPlatformCapability = (typeof PACK_PLATFORM_CAP)[keyof typeof PACK_PLATFORM_CAP];")
    lines.append("export type PackLocalCapability = (typeof PACK_LOCAL_CAP)[keyof typeof PACK_LOCAL_CAP];")
    lines.append("export type PackCapability = (typeof PACK_CAP)[keyof typeof PACK_CAP];")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
