/* Generated by scripts/gen-pack-capabilities.py — do not edit by hand. */
/* Source: internal/packs/capability_tokens.json */

/** Thin NJ platform + official domain capability tokens. */
export const PACK_PLATFORM_CAP = {
  CUSTOMER_PACK: 'customer-pack',
  SETTINGS_OVERLAY: 'settings-overlay',
  WORKSPACE_GUIDE: 'workspace-guide',
  IDE_V2: 'ide-v2',
  IDE_V3_COMPOSER: 'ide-v3-composer',
  IDE_V4: 'ide-v4',
  GIT_REST: 'git-rest',
  INLINE_COMPLETION: 'inline-completion',
  CAD_API: 'cad-api',
  CAD_VIEWER: 'cad-viewer',
  CAD_WORKBENCH: 'cad-workbench',
  LORA_TRAINING: 'lora-training',
  LORA_COMPOSE: 'lora-compose',
  LORA_ADAPTERS: 'lora-adapters',
  PERSONAL_LEARNING: 'personal-learning',
  AWS_API: 'aws-api',
  AWS_SSO: 'aws-sso',
  INCIDENT_API: 'incident-api',
  JIRA_INTEGRATION: 'jira-integration',
  INCIDENT_TRIAGE: 'incident-triage',
  GITHUB_ISSUES_INTEGRATION: 'github-issues-integration',
  LINEAR_INTEGRATION: 'linear-integration',
  PAGERDUTY_INTEGRATION: 'pagerduty-integration',
  SENTRY_INTEGRATION: 'sentry-integration',
  WEB_BROWSER: 'web-browser',
  WEB_PREVIEW: 'web-preview',
  WEB_BROWSER_WORKBENCH: 'web-browser-workbench',
  BIOLOGY_API: 'biology-api',
  BIOLOGY_WORKBENCH: 'biology-workbench',
  BIOLOGY_SIDECAR: 'biology-sidecar',
  MUSIC_GENERATION: 'music-generation',
  MUSIC_WORKBENCH: 'music-workbench',
  MUSIC_SIDECAR: 'music-sidecar',
  MODEL_ARENA: 'model-arena',
  MODEL_ARENA_SIDECAR: 'model-arena-sidecar',
  MODEL_ARENA_WORKBENCH: 'model-arena-workbench',
  LORA_TRAINING_SIDECAR: 'lora-training-sidecar',
} as const;

/** Documented pack-local capability ids (capability_defs); prefer hub registry at runtime. */
export const PACK_LOCAL_CAP = {
  BROWSER_SIDECAR: 'browser-sidecar',
  SD_MCP_SIDECAR: 'sd-mcp-sidecar',
  AWS_SIDECAR: 'aws-sidecar',
  CAD_SIDECAR: 'cad-sidecar',
  INCIDENT_SIDECAR: 'incident-sidecar',
  ROOM_CHAT: 'room-chat',
  MODEL_ARENA_LAUNCHER: 'model-arena-launcher',
  AI_INTERVIEW_SIDECAR: 'ai-interview-sidecar',
  AI_INTERVIEW_LAUNCHER: 'ai-interview-launcher',
  PHOENIX_IMPORT: 'phoenix-import',
  SCAN_SUMMARY_API: 'scan-summary-api',
  SCAN_SUMMARY_VIEWER: 'scan-summary-viewer',
  SCAN_ANALYSIS_VIEWER: 'scan-analysis-viewer',
  SECONDARY_ANALYSIS_API: 'secondary-analysis-api',
  SECONDARY_ANALYSIS_VIEWER: 'secondary-analysis-viewer',
  SECONDARY_ANALYSIS_PYTHON: 'secondary-analysis-python',
} as const;

export const PACK_CAP = { ...PACK_PLATFORM_CAP, ...PACK_LOCAL_CAP } as const;

export type PackPlatformCapability = (typeof PACK_PLATFORM_CAP)[keyof typeof PACK_PLATFORM_CAP];
export type PackLocalCapability = (typeof PACK_LOCAL_CAP)[keyof typeof PACK_LOCAL_CAP];
export type PackCapability = (typeof PACK_CAP)[keyof typeof PACK_CAP];
